name: Pull-request for Java Maven Project

on:
  push:
    branches:
      - main
      - feature_branch
  pull_request:
    branches:
      - feature_branch
   
jobs:
  build_maven:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8,11,17,21,25]
        distribution: [temurin, zulu, microsoft]
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java
      
      - name: Build and Test
        run: mvn clean verify

      - name: Upload Build Artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: maven-jar-${{ matrix.java }}-${{ matrix.distribution }}
          path: target/*.jar
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.java }}-${{ matrix.distribution }}
          path: target/surefire-reports/
      - name: Perform Code Quality Analysis
        uses: github/codeql-action/analyze@v4
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/target/surefire-reports/**/*.xml"
          comment_mode: always
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish_output
