name: Pull-request for Java Maven Project

on:
  push:
    branches:
      - main
      - feature_branch
  pull_request:
    branches:
      - feature_branch

jobs:
  build_maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java
      
      - name: Build and Test
        run: mvn clean verify

      - name: Upload Build Artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: maven-jar
          path: target/*.jar
